### ISSUE TITLE
For Musicvideos, optionally use  'Poster.jpg' for Thumb.jpg and Fanart.jpg

### ISSUE THREAD

**Issue by frankpc3** [xbmc/skin.confluence#198]
My 'Kodi user friends' and I enjoy using Confluence for our Kodi Skin.  We use local graphics for fanart, poster, and thumb for each musicvideo.  Quite often we only have one or two graphics that are used for all three.  Hours and hours are spent either assigning the 'Poster' graphic to be used for thumbnail and often for fanart.  Or the 'poster' graphic is copied one or two times for each music video and renamed to be used for thumb and often for fanart and saved to each musicvideo folder.

Many many hours of work would be saved if Confluence had two settings available to allow the 'poster' graphic to be used as an alternate for thumb and/or fanart.

As information, the Estuary skin has a setting to allow the use of Poster to be used for the thumb graphic.

Currently each of our musicvideo folder's contents is similar to the following:

Alicia Keys - Unplugged.iso
Alicia Keys - Unplugged.nfo
Alicia Keys - Unplugged-poster. jpg
Alicia Keys - Unplugged-fanart.jpg
Alicia Keys - Unplugged-thumb.jpg

Thank you for your consideration.

Frankpc

**Comment by DaVukovic** [comment]
As mentioned at the thread at our forums..I'll have a look into it. Please just give me some time.

**Comment by frankpc3** [comment]
Thank you DaVukovic.

**Comment by DaVukovic** [comment]
I'm currently working on this. It's already partially working. Found some other flaws with current textures and images. I probably need to create a new one or might need  helping creating one as the default `ListItem.Icon` has the wrong format if a poster is missing and we might need a fallback-image. 

But that's somewhat easy to solve.

**Comment by frankpc3** [comment]
Great news !!  Thank you for your hard work and time.

A lot of people will appreciate your efforts.

**Comment by DaVukovic** [comment]
I also asked at the team. 

What would you expect to see at the "MediaInfo"-view for musicvideos. Currently it would show a thumb from the videos (like for TV-show episodes). For movies this view will shot the fanart of the movie.

With my setting it would either show the poster (if enabled) or currently a thumb of the video (if disabled). I'm asking myself if
* my setting should have an affect at this at all
* if my setting should have an affect, either show the thumb (like for tv-show episodes) or probably the fanart (like for movies)

So I thought I'm asking what you might expect to see to get more opinions ;)

**Comment by frankpc3** [comment]
Wow!  Great news.

When we look at the Media Info view for musicvideos, we see fanart in the background and a poster or thumb on the right side.  If there is no unique fanart assigned, then the poster or thumb shows in the background.  So either arrangement is great.  

Seems your setting would have an effect on the view.  It would show the fanart as background if available, otherwise the poster if available.  The thumb would be fine too.  And on the right side, the poster would show if available.  If thumb was available and not the poster, then the thumb would be fine.

When we are selecting a video, it is nice to see something familiar to help make the selection.  We'd prefer not to see a random frame from the music video itself since some of those random frames are blank or not indicative or recognizable of what the video actually is.

There is also the icon art.  I assign the poster or thumb to that.  Which ever one is available is perfect.

Again, I'm amazed with the consideration and detail you are giving to this project.  It is obviously much more involved than what one sees on the surface.  Thank you for you hard work and efforts to make it perfect.

**Comment by DaVukovic** [comment]
Cool. So my current state can stay as it is. Actually it's in the statte:

If setting enabled: 
* show poster instead of thumbs for the views Thumbnail and  Media info. The views List and Big list will poster anyway and I won't change that

If the setting is disabled: 
* Media info and Thumbnail view will shot thumbs. 

For all views it will show the fanart if available, otherwise the standard skin backgroung

I won't add a mixed view. For example....if the setting is enabled, then show the poster if available and if not, show the thumb. The problem here is, that both textures will have a different format. A poster is higher then its width and a thumbs is wider than its height. We can talk about that in the future, but for the time being I'll decide for one or the other and if one isn't available show some kind of standard video icon which is in the same format of either the poster or the thumb. 

I highly expect that music enthusiast who love music videos that much, will take care of matching images for their libraries. I'm using this section for my concert rips and not for single musiv videos. So I mostly care about posters and the List view. 

I guess we can agree on that.

And yes, things sometimes sound eady, like "Could we please have a setting to decide for a specific texture" ;) 

In the end it's multiple conditions you have to take care of and you have to make sure you don't break things for other content which uses the same views. So you change a condition, and then check ANY kind of content in ANY view available with (hopefully) ANY kind of texture which might be available or not. Even if I know that I somewhat guess I'll forget some corner case. But we'll have the bug tracker for that :D ;)

Thanks for your nice words. Much appreciated. It's always nice to see that ppl are thankful for what we are doing. It makes more fun this way :+1:

**Comment by frankpc3** [comment]
Sounds like you have thought the whole process through thoroughly.  And that your final solution is perfect.  No one can ask for more than that.  I like fanart and to use it where appropriate works well.

I do endeavor to find appropriate covers for the music videos.  I get most of them from Amazon... Either bluray or dvd covers as appropriate.  And for mixed single song videos, I choose something that addresses 'Various artist' kind of DVDs.

I can imagine that there are so many considerations taken into account when building something like this.  And I and a lot of others are looking forward to what you've accomplished.  Thank you.

**Comment by DaVukovic** [comment]
Pull request is opened. Currently under review. If it gets merged, I'll create a new branch and will then submit it to the repo.

**Comment by frankpc3** [comment]
wow... Great news!  Is there a group of people who review your work to decide whether your proposed changes make their way into the finished product?  Or perhaps suggest minor changes to meet standards?

Again, thank you for your hard work on this.

**Comment by Hitcher** [comment]
This can be closed as it was merged - https://github.com/xbmc/skin.confluence/pull/200
