### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by edenmedia** [xbmc/skin.confluence#223]
Could I please know why the Confluence skin is not updated in the kodi repository? 
It's been more than 7 months and still hasn't been updated. 
In the official repo there is only version 4.7.13 and not the version present in this git (4.7.15).
Maybe because the new update has to be released in a separate release specifically for Nexus? Thank you

**Comment by Frencman** [comment]
Just updated Kodi to Omega 21 on FireTV Cube.  All seems OK except Favourites won’t display.  Data is still there.  I tried to create a new favorite but it will not display from my list.  Thought you may like to know.
Thanx - PaulT

**Comment by HitcherUK** [comment]
Simple answer is no one has the time spare right now to update it for the latest skin changes.

**Comment by bossanova808** [comment]
Well TBH in this case it's technically not so much that the work has not been done - https://github.com/xbmc/skin.confluence/pull/194

...but rather that an actual release of this work has never been made, so lots of folks aren't seeing this.  Bit frustrating really given the work was actually done...(although even if a release were to be lined up, the approvals process seems completely stalled right now too - https://github.com/xbmc/repo-scripts/pulls)

Anyhoo, with those changes, Favourites works ok (as a window) in Omega, with Confluence (although could certainly yet be improved I'm sure).  I've not yet seen any eal issues with Confluence/Omega TBH (although I've only just started with it, to test the addons I am resposible for still work..).

There is a weird new arrow next to a bunch of shows - seemingly ones Kodi thinks are 'In Progress' - which is kind of unnecessary and annoying (since it seems to be wrong on occasions as well) - but other that that very minor glitch, all the normal things seem to be working well.

**Comment by Frencman** [comment]
I see mention of a Favourites window in many places.  How can I display this window?
Thanx - PaulT

**Comment by Frencman** [comment]
I’ve gone without my favorites for now as they are all shortcuts.  I just go down the addon's menu until I get to where I want to be.

**Comment by tavoc** [comment]
Usingnthe ZIP from github works in omega. Simply download it and installiert it like an addon (ZIP)

**Comment by puppinoo** [comment]
Just wanted to thanks @bossanova808 and whoever else fixed this skin which even if old still remains my favourite (and Favorites was my biggest issues). Please dont give up on It and thanks again.

Cheers.

**Comment by bossanova808** [comment]
You are welcome.  Just a shame it hasn't been properly released - would make it a lot easier for folks!

I plan to look at the new movie versions thing once the dust settles on that, too.  But I don't have gaming set up (or any interest) so that would have to be someone else.  But hopefully we can keep the core stuff working a while yet!

**Comment by Frencman** [comment]
Hi Jeremy - I’ve been trying to make sense of these messages to use the workaround but I am a newbie when it comes to GitHub.  Is the zip file located somewhere that I can make Kodi access it (through the file/zip/repo method or similar)?  Maybe the process is too complicated or I do not have the skills to manage this at this time and should just wait?  I know there are .xml files but have no idea where they are or how to modify or replace them within Kodi. 
Either way, another thank you for what you’ve done for those that know what they’re doing 😉.

**Comment by bossanova808** [comment]
Just go to the front page of this repo, green 'Code' dropdown, and then choose 'Download Zip'.  Then in Kodi install addon from zip, and point at the downloaded zip.  Done!

![image](https://github.com/xbmc/skin.confluence/assets/731309/71804b08-2af3-498a-bb77-061ab60100eb)

**Comment by Frencman** [comment]
THANK YOU !!!
I now have my favorites back but in a different format!
Now to edit, rename, move etc.
Paul

**Comment by Frencman** [comment]
Kudos out to everyone who worked on this and to Jeremy for helping me learn how to install it from GitHub.  I have updated my FireStick, FireCube, and Onn device. The Fire products seem to not let me move the ordering but by changing and grouping them by color it really looks GREAT !!!
In the past I chose to have my Favourites as the start-up option but when I did that it crashed completely - only option was to uninstall Kodi and reinstall it and losing all work I did 😡.  Now with Kodi 21 Beta 2 on all devices they skip the Home Screen and go right to my Favorites menu - YAY.
Thanx Again - Paul

**Comment by bossanova808** [comment]
(for the future note that you could e.g. just manually edit guisettings.xml to remove the startup to favourites option rather than needing a complete re-install, should you ever get into trouble again...)

I am not sure I am following the rest, if that's a bug report.  With older Kodi, it should use the old Dialog Favourites and with newer the new Window Favourites, so nothing should break under any version, really.

I don't have any Fire device experience so I don't know if that changes anything, and I've lost track of the changes I did a bit, it was quite a while ago, but if you're having any issues best to open a new issue with a proper bug report (exactly what versions of Kodi you're using, how to reproduce etc)...

**Comment by puppinoo** [comment]
Hi,
Yesterday I tried to install latest Omega nightly. After launched it deprecated Confluence (with a bunch of other plugins).
Can this be fixed?

Thanks.

**Comment by Frencman** [comment]
No issues Jeremy.  Just interesting differences between Fire and Onn.
Thanx Again - Paul

**Comment by bossanova808** [comment]
> Hi, Yesterday I tried to install latest Omega nightly. After launched it disabled Confluence (with a bunch of other plugins) saying they were deprecated. Can this be fixed?
> 
> Thanks.

Yes _after_ beta 2 they bumped the skin 'ABI' - so currently Confluence as it stands here (even with all my changes in the code, as you receive when you download the .zip) - is only compatible _up to_ Beta 2, but **not** _beyond Beta 2_.  You should thus revert to Beta 2 for now and a avoid nightlies for a bit (or use another skin if you need to be on nightlies I guess).

Given the mess/rapid flux with the new video versions feature, it's not quite time yet to do the skin fixups for that, and it probably means Beta 3 is delayed a bit.  Once all that settles I'll look at it and work out how hard that will be to support, I guess!

**Comment by guenniguenzelsen** [comment]
Open "addon.xml"
Change the text xbmx.gui 5.15.0 to xbmc.gui 5.17.0 and the skin will work with the latest nightlies again.

**Comment by jdevrie** [comment]
Great! That worked.
Thnx.

**Comment by Hitcher** [comment]
Had some free time so I've updated Confluence for Nexus.

https://github.com/xbmc/skin.confluence/pull/229

**Comment by jdevrie** [comment]
> Had some free time so I've updated Confluence for Nexus.
> 
> #229

Will this work on Omega when I change the compatibility with Abi  to V5.17.0?

**Comment by bossanova808** [comment]
@Hitcher This is fabulous to see, and so very much appreciated.  Am looking forward to playing with this soon!
