### ISSUE TITLE
Error adding Confluence in Kodi 21.0 Omega

### ISSUE THREAD

**Issue by gmpeet** [xbmc/skin.confluence#245]
I tried to add the latest version Confluence 4.8 to Kodi 21.0 Omega,
downloaden from both the Kodi Omega add-on and from the github

I get an error, in Dutch, 
NL: "De afhankelijkheid op xbmc.gui versie 5.16.0 kan niet worden voldaan"
In English,
EN: "The dependacy on xbmc.gui version 5.16.0 could not be satisfied".

Confluence add-on skin will not install on my system for now

**Comment by bossanova808** [comment]
Confluence for Omega is currently undergoing review, and once that is done, will then soon enter the standard Kodi repo and be generally available - see: https://github.com/xbmc/skin.confluence/pull/244 for progress/conversation.

In the mean time, if you don't want to wait, you can download a zip with all these changes, from Hitcher's repo: https://github.com/Hitcher/skin.confluence/archive/refs/heads/master.zip

...and then in your Kodi 'install from zip' to get that working.  

But do note, when you install from zip, you effectively break the standard Kodi add-on updates system, so you won't automatically get future updates for Confluence as they then come later.  So if you do install the zip, remember that once Confluence is back to being officially available from the Kodi master repository, you'll want to install the version from there over the top, so that you then do get the normal updates going forward.

_(Hitcher has done a massive amount of work upgrading the skin for Omega, and all us Confluence users are very very grateful!)_
